# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dimg < Formula
  desc "TUI for docker pull"
  homepage "https://github.com/kohbis/dimg"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/dimg/releases/download/v0.1.0/dimg_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "6be358de425f05b797d07c56c8d905f1c87149c69cf4fe814be5306e7b0a3996"

      def install
        bin.install "dimg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kohbis/dimg/releases/download/v0.1.0/dimg_0.1.0_Darwin_arm64.tar.gz"
      sha256 "94879bd887f7ec05156fe2aa4ebf942d44115ab716b74ed71297e3f8828cdc9d"

      def install
        bin.install "dimg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kohbis/dimg/releases/download/v0.1.0/dimg_0.1.0_Linux_arm64.tar.gz"
      sha256 "999509ceb1351788842119847499de70c5132cdadaf23b72d0a7c38a4d14d29d"

      def install
        bin.install "dimg"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kohbis/dimg/releases/download/v0.1.0/dimg_0.1.0_Linux_x86_64.tar.gz"
      sha256 "7c41f7df56d6e27ec81478bbc2f644fef2afb4f01997aa1c6fa5663083960e60"

      def install
        bin.install "dimg"
      end
    end
  end
end
